### PR TITLE
chore!: use `nvim_create_{augroup,autocmd}`

### PR DESCRIPTION
**Pull request by numToStr**
Now that https://github.com/neovim/neovim/pull/14661 is merged we can
use lua to create autocommands and autogroups.

### CODE REVIEW

**Comment by syphar** [comment]
@numToStr while I like the improvements with `nvim_create_{augroup,autocmd}`, this breaks the plugin for users of stable version. 

If this was intended I understand, but then the nightly requirement should be in the readme, should it?

**Comment by realvikas** [comment]
@syphar Sorry for the trouble. If you don't mind changing your config, you can jump to this commit 6bfcf7da965a03fd1e170aa6870b92b16bf739ee which should work for you. I'll update the readme for now but I also think that 0.7 is coming soon ;)

**Comment by numToStr** [comment]
@syphar Sorry for the trouble. If you don't mind changing your config, you can jump to this commit https://github.com/numToStr/Navigator.nvim/commit/6bfcf7da965a03fd1e170aa6870b92b16bf739ee which should work for you. I'll update the readme for now but I also think that 0.7 is coming soon ;)

**Comment by syphar** [comment]
Yeah, I already switched to the commit before. 

>  I'll update the readme for now 
thanks! 

> but I also think that 0.7 is coming soon ;)

that would be even more awesome, not only because of lua augroups :)

**Comment by numToStr** [comment]
Just a heads up. I've added a patch [6c50f27](https://github.com/numToStr/Navigator.nvim/commit/6c50f278482dc5388743cb5c6eddb146059252f9) for stable users which should prevent that `commit` workaround.

**Pull request merged**
